package thepaperpilot.strange.Levels;

import com.badlogic.gdx.Game;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.math.Rectangle;
import com.badlogic.gdx.utils.Json;

public class LevelGenerator {
    private final static Json json = new Json();

    public static void main(String[] args) {
        new LwjglApplication(new Game() {
            @Override
            public void create() {
                Level.LevelPrototype levelPrototype = new Level.LevelPrototype();
                levelPrototype.first = "first";

                levelPrototype.scenes = new Scene.ScenePrototype[4];
                levelPrototype.scenes[0] = new Scene.ScenePrototype();
                Scene.ScenePrototype scene = levelPrototype.scenes[0];
                scene.name = "first";
                scene.background = "bathroom";
                scene.entities = new Entity.EntityPrototype[4];
                scene.entities[0] = new Entity.EntityPrototype();
                Entity.EntityPrototype entity = scene.entities[0];
                entity.type = "CLOCK";
                entity.x = 192;
                entity.y = 96;
                entity.visible = true;
                entity.attributes.put("texture", "clock");
                entity.attributes.put("numFrames", "12");
                entity.attributes.put("time", "1");
                scene.entities[1] = new Entity.EntityPrototype();
                entity = scene.entities[1];
                entity.type = "IMAGE";
                entity.name = "schoolDoor1";
                entity.x = 10;
                entity.y = 32;
                entity.visible = true;
                entity.attributes.put("texture", "schoolDoor");
                entity.successEffects = new Effect.EffectPrototype[1];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "DIALOGUE";
                entity.successEffects[0].attributes.put("targetScene", "first");
                entity.successEffects[0].attributes.put("dialogue", "door1");
                scene.entities[2] = new Entity.EntityPrototype();
                entity = scene.entities[2];
                entity.type = "IMAGE";
                entity.name = "fireAlarm";
                entity.x = 210;
                entity.y = 60;
                entity.visible = true;
                entity.attributes.put("texture", "fireAlarmPuzzle");
                entity.requiredItems = new String[]{"hammer"};
                entity.successEffects = new Effect.EffectPrototype[4];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "CHANGE_APPEARANCE";
                entity.successEffects[0].attributes.put("targetScene", "first");
                entity.successEffects[0].attributes.put("targetEntity", "fireAlarm");
                entity.successEffects[0].attributes.put("texture", "fireAlarmPuzzleBroken");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "SAY";
                entity.successEffects[1].attributes.put("targetScene", "first");
                entity.successEffects[1].attributes.put("message", "whoah! what was a gun doing in there?");
                entity.successEffects[2] = new Effect.EffectPrototype();
                entity.successEffects[2].type = "ADD_ITEM";
                entity.successEffects[2].attributes.put("targetItem", "gun");
                entity.successEffects[3] = new Effect.EffectPrototype();
                entity.successEffects[3].type = "REMOVE_ITEM";
                entity.successEffects[3].attributes.put("targetItem", "hammer");
                entity.failEffects = new Effect.EffectPrototype[1];
                entity.failEffects[0] = new Effect.EffectPrototype();
                entity.failEffects[0].type = "SAY";
                entity.failEffects[0].attributes.put("targetScene", "first");
                entity.failEffects[0].attributes.put("message", "I need to find something to break this with");
                scene.entities[3] = new Entity.EntityPrototype();
                entity = scene.entities[3];
                entity.type = "IMAGE";
                entity.name = "soap";
                entity.x = 230;
                entity.y = 16;
                entity.visible = true;
                entity.attributes.put("texture", "soapWorld");
                entity.successEffects = new Effect.EffectPrototype[2];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "REMOVE_ENTITY";
                entity.successEffects[0].attributes.put("targetScene", "first");
                entity.successEffects[0].attributes.put("targetEntity", "soap");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "ADD_ITEM";
                entity.successEffects[1].attributes.put("targetItem", "soap");

                levelPrototype.scenes[1] = new Scene.ScenePrototype();
                scene = levelPrototype.scenes[1];
                scene.name = "second";
                scene.background = "outside";
                scene.previous = "first";
                scene.entities = new Entity.EntityPrototype[3];
                scene.entities[0] = new Entity.EntityPrototype();
                entity = scene.entities[0];
                entity.type = "CLOCK";
                entity.x = 148;
                entity.y = 55;
                entity.visible = true;
                entity.attributes.put("texture", "clock");
                entity.attributes.put("numFrames", "12");
                entity.attributes.put("time", "2");
                scene.entities[1] = new Entity.EntityPrototype();
                entity = scene.entities[1];
                entity.type = "ANIMATION";
                entity.name = "cat1";
                entity.x = 81;
                entity.y = 10;
                entity.visible = true;
                entity.attributes.put("texture", "catIdle");
                entity.attributes.put("numFrames", "14");
                entity.attributes.put("speed", Float.toString(1 / 6f));
                entity.requiredItems = new String[]{"cat food"};
                entity.successEffects = new Effect.EffectPrototype[5];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "CHANGE_APPEARANCE";
                entity.successEffects[0].attributes.put("targetScene", "second");
                entity.successEffects[0].attributes.put("targetEntity", "cat1");
                entity.successEffects[0].attributes.put("texture", "catEating");
                entity.successEffects[0].attributes.put("numFrames", "2");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "SAY";
                entity.successEffects[1].attributes.put("targetScene", "second");
                entity.successEffects[1].attributes.put("message", "aww. it looks so happy now!");
                entity.successEffects[2] = new Effect.EffectPrototype();
                entity.successEffects[2].type = "ADD_ENTITY";
                entity.successEffects[2].attributes.put("targetScene", "fourth");
                entity.successEffects[2].attributes.put("targetEntity", "sugar");
                entity.successEffects[3] = new Effect.EffectPrototype();
                entity.successEffects[3].type = "CHANGE_APPEARANCE";
                entity.successEffects[3].attributes.put("targetScene", "fourth");
                entity.successEffects[3].attributes.put("targetEntity", "bird");
                entity.successEffects[3].attributes.put("type", "ANIMATION");
                entity.successEffects[3].attributes.put("texture", "blueJayIdle");
                entity.successEffects[3].attributes.put("numFrames", "14");
                entity.successEffects[3].attributes.put("speed", Float.toString(1 / 6f));
                entity.successEffects[4] = new Effect.EffectPrototype();
                entity.successEffects[4].type = "REMOVE_ITEM";
                entity.successEffects[4].attributes.put("targetItem", "cat food");
                entity.failEffects = new Effect.EffectPrototype[1];
                entity.failEffects[0] = new Effect.EffectPrototype();
                entity.failEffects[0].type = "SAY";
                entity.failEffects[0].attributes.put("targetScene", "second");
                entity.failEffects[0].attributes.put("message", "This cat looks bored. I hear cats hunt birds when they're bored.");
                entity.doneEffects = new Effect.EffectPrototype[1];
                entity.doneEffects[0] = new Effect.EffectPrototype();
                entity.doneEffects[0].type = "SAY";
                entity.doneEffects[0].attributes.put("targetScene", "second");
                entity.doneEffects[0].attributes.put("message", "aww. it looks so happy now!");
                scene.entities[2] = new Entity.EntityPrototype();
                entity = scene.entities[2];
                entity.type = "IMAGE";
                entity.name = "dogBone";
                entity.x = 200;
                entity.y = 14;
                entity.visible = true;
                entity.attributes.put("texture", "dogBoneWorld");
                entity.successEffects = new Effect.EffectPrototype[2];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "REMOVE_ENTITY";
                entity.successEffects[0].attributes.put("targetScene", "second");
                entity.successEffects[0].attributes.put("targetEntity", "dogBone");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "ADD_ITEM";
                entity.successEffects[1].attributes.put("targetItem", "dog bone");

                levelPrototype.scenes[2] = new Scene.ScenePrototype();
                scene = levelPrototype.scenes[2];
                scene.name = "third";
                scene.background = "school";
                scene.previous = "first";
                scene.entities = new Entity.EntityPrototype[4];
                scene.entities[0] = new Entity.EntityPrototype();
                entity = scene.entities[0];
                entity.type = "CLOCK";
                entity.x = 192;
                entity.y = 96;
                entity.visible = true;
                entity.attributes.put("texture", "clock");
                entity.attributes.put("numFrames", "12");
                entity.attributes.put("time", "3");
                scene.entities[1] = new Entity.EntityPrototype();
                entity = scene.entities[1];
                entity.type = "IMAGE";
                entity.name = "door2";
                entity.x = 48;
                entity.y = 16;
                entity.visible = true;
                entity.attributes.put("texture", "schoolDoor");
                entity.requiredItems = new String[]{"keys"};
                entity.doneEffects = new Effect.EffectPrototype[1];
                entity.doneEffects[0] = new Effect.EffectPrototype();
                entity.doneEffects[0].type = "CHANGE_SCREEN";
                entity.doneEffects[0].attributes.put("targetScene", "fourth");
                entity.successEffects = new Effect.EffectPrototype[1];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "REMOVE_ITEM";
                entity.successEffects[0].attributes.put("targetItem", "keys");
                entity.failEffects = new Effect.EffectPrototype[1];
                entity.failEffects[0] = new Effect.EffectPrototype();
                entity.failEffects[0].type = "SAY";
                entity.failEffects[0].attributes.put("targetScene", "third");
                entity.failEffects[0].attributes.put("message", "it's locked");
                scene.entities[2] = new Entity.EntityPrototype();
                entity = scene.entities[2];
                entity.type = "IMAGE";
                entity.name = "alyssa";
                entity.x = 192;
                entity.y = 14;
                entity.visible = true;
                entity.attributes.put("texture", "AlyssaSoapPuzzle");
                entity.requiredItems = new String[]{"soap"};
                entity.successEffects = new Effect.EffectPrototype[3];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "SAY";
                entity.successEffects[0].attributes.put("targetScene", "third");
                entity.successEffects[0].attributes.put("message", "thank you alyssa!");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "ADD_ITEM";
                entity.successEffects[1].attributes.put("targetItem", "keys");
                entity.successEffects[2] = new Effect.EffectPrototype();
                entity.successEffects[2].type = "REMOVE_ITEM";
                entity.successEffects[2].attributes.put("targetItem", "soap");
                entity.doneEffects = new Effect.EffectPrototype[1];
                entity.doneEffects[0] = new Effect.EffectPrototype();
                entity.doneEffects[0].type = "SAY";
                entity.doneEffects[0].attributes.put("targetScene", "third");
                entity.doneEffects[0].attributes.put("message", "I already have her the soap. Wasn't the tutorial enough?");
                entity.failEffects = new Effect.EffectPrototype[1];
                entity.failEffects[0] = new Effect.EffectPrototype();
                entity.failEffects[0].type = "DIALOGUE";
                entity.failEffects[0].attributes.put("targetScene", "third");
                entity.failEffects[0].attributes.put("dialogue", "Alyssa1");
                scene.entities[3] = new Entity.EntityPrototype();
                entity = scene.entities[3];
                entity.type = "IMAGE";
                entity.name = "soda";
                entity.x = 80;
                entity.y = 16;
                entity.visible = true;
                entity.attributes.put("texture", "sodaWorld");
                entity.successEffects = new Effect.EffectPrototype[2];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "REMOVE_ENTITY";
                entity.successEffects[0].attributes.put("targetScene", "third");
                entity.successEffects[0].attributes.put("targetEntity", "soda");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "ADD_ITEM";
                entity.successEffects[1].attributes.put("targetItem", "soda");

                levelPrototype.scenes[3] = new Scene.ScenePrototype();
                scene = levelPrototype.scenes[3];
                scene.name = "fourth";
                scene.background = "outside";
                scene.previous = "third";
                scene.obstacles.put("dog", new Rectangle(160, 0, 16, 144));
                scene.entities = new Entity.EntityPrototype[8];
                scene.entities[0] = new Entity.EntityPrototype();
                entity = scene.entities[0];
                entity.type = "CLOCK";
                entity.x = 148;
                entity.y = 55;
                entity.visible = true;
                entity.attributes.put("texture", "clock");
                entity.attributes.put("numFrames", "12");
                entity.attributes.put("time", "4");
                scene.entities[1] = new Entity.EntityPrototype();
                entity = scene.entities[1];
                entity.type = "IMAGE";
                entity.name = "tirestack";
                entity.x = 230;
                entity.y = 13;
                entity.visible = true;
                entity.attributes.put("texture", "tirestack");
                entity.successEffects = new Effect.EffectPrototype[1];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "CHANGE_SCREEN";
                entity.successEffects[0].attributes.put("targetScene", "fifth");
                scene.entities[2] = new Entity.EntityPrototype();
                entity = scene.entities[2];
                entity.type = "IMAGE";
                entity.name = "stairs";
                entity.x = 0;
                entity.y = 7;
                entity.visible = true;
                entity.attributes.put("texture", "stairs");
                entity.successEffects = new Effect.EffectPrototype[1];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "CHANGE_SCREEN";
                entity.successEffects[0].attributes.put("targetScene", "sixth");
                scene.entities[3] = new Entity.EntityPrototype();
                entity = scene.entities[3];
                entity.type = "ANIMATION";
                entity.name = "dog1";
                entity.x = 160;
                entity.y = 13;
                entity.visible = true;
                entity.attributes.put("texture", "dogIdle");
                entity.attributes.put("numFrames", "14");
                entity.attributes.put("speed", Float.toString(1 / 6f));
                entity.requiredItems = new String[]{"dog bone"};
                entity.successEffects = new Effect.EffectPrototype[4];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "CHANGE_APPEARANCE";
                entity.successEffects[0].attributes.put("targetScene", "fourth");
                entity.successEffects[0].attributes.put("targetEntity", "dog1");
                entity.successEffects[0].attributes.put("texture", "dogHappy");
                entity.successEffects[0].attributes.put("numFrames", "2");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "SAY";
                entity.successEffects[1].attributes.put("targetScene", "fourth");
                entity.successEffects[1].attributes.put("message", "look how cute it is!");
                entity.successEffects[2] = new Effect.EffectPrototype();
                entity.successEffects[2].type = "REMOVE_BARRIER";
                entity.successEffects[2].attributes.put("targetScene", "fourth");
                entity.successEffects[2].attributes.put("targetObstacle", "dog");
                entity.successEffects[3] = new Effect.EffectPrototype();
                entity.successEffects[3].type = "REMOVE_ITEM";
                entity.successEffects[3].attributes.put("targetItem", "dog bone");
                entity.failEffects = new Effect.EffectPrototype[1];
                entity.failEffects[0] = new Effect.EffectPrototype();
                entity.failEffects[0].type = "SAY";
                entity.failEffects[0].attributes.put("targetScene", "fourth");
                entity.failEffects[0].attributes.put("message", "This dog won't let me through. It looks hungry");
                entity.doneEffects = new Effect.EffectPrototype[1];
                entity.doneEffects[0] = new Effect.EffectPrototype();
                entity.doneEffects[0].type = "SAY";
                entity.doneEffects[0].attributes.put("targetScene", "fourth");
                entity.doneEffects[0].attributes.put("message", "The dog is much happier now that it has a bone");
                scene.entities[4] = new Entity.EntityPrototype();
                entity = scene.entities[4];
                entity.type = "IMAGE";
                entity.name = "bird";
                entity.x = 73;
                entity.y = 10;
                entity.visible = true;
                entity.attributes.put("texture", "blueJayDead");
                scene.entities[5] = new Entity.EntityPrototype();
                entity = scene.entities[5];
                entity.type = "IMAGE";
                entity.name = "cat food";
                entity.x = 170;
                entity.y = 13;
                entity.visible = true;
                entity.attributes.put("texture", "catFoodWorld");
                entity.successEffects = new Effect.EffectPrototype[2];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "REMOVE_ENTITY";
                entity.successEffects[0].attributes.put("targetScene", "fourth");
                entity.successEffects[0].attributes.put("targetEntity", "cat food");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "ADD_ITEM";
                entity.successEffects[1].attributes.put("targetItem", "cat food");
                scene.entities[6] = new Entity.EntityPrototype();
                entity = scene.entities[6];
                entity.type = "IMAGE";
                entity.name = "weed killer";
                entity.x = 21;
                entity.y = 7;
                entity.visible = true;
                entity.attributes.put("texture", "weedKillerWorld");
                entity.successEffects = new Effect.EffectPrototype[2];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "REMOVE_ENTITY";
                entity.successEffects[0].attributes.put("targetScene", "fourth");
                entity.successEffects[0].attributes.put("targetEntity", "weed killer");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "ADD_ITEM";
                entity.successEffects[1].attributes.put("targetItem", "weed killer");
                scene.entities[7] = new Entity.EntityPrototype();
                entity = scene.entities[7];
                entity.type = "IMAGE";
                entity.name = "sugar";
                entity.x = 120;
                entity.y = 10;
                entity.visible = false;
                entity.attributes.put("texture", "sugarWorld");
                entity.successEffects = new Effect.EffectPrototype[2];
                entity.successEffects[0] = new Effect.EffectPrototype();
                entity.successEffects[0].type = "REMOVE_ENTITY";
                entity.successEffects[0].attributes.put("targetScene", "fourth");
                entity.successEffects[0].attributes.put("targetEntity", "sugar");
                entity.successEffects[1] = new Effect.EffectPrototype();
                entity.successEffects[1].type = "ADD_ITEM";
                entity.successEffects[1].attributes.put("targetItem", "sugar");

                levelPrototype.items = new Item.ItemPrototype[21];
                levelPrototype.items[0] = new Item.ItemPrototype();
                levelPrototype.items[0].name = "alcohol";
                levelPrototype.items[0].texture = "alcohol";
                levelPrototype.items[1] = new Item.ItemPrototype();
                levelPrototype.items[1].name = "bottles";
                levelPrototype.items[1].texture = "bottles";
                levelPrototype.items[2] = new Item.ItemPrototype();
                levelPrototype.items[2].name = "camera";
                levelPrototype.items[2].texture = "camera";
                levelPrototype.items[3] = new Item.ItemPrototype();
                levelPrototype.items[3].name = "cat food";
                levelPrototype.items[3].texture = "catFood";
                levelPrototype.items[4] = new Item.ItemPrototype();
                levelPrototype.items[4].name = "dog bone";
                levelPrototype.items[4].texture = "dogBone";
                levelPrototype.items[5] = new Item.ItemPrototype();
                levelPrototype.items[5].name = "duct tape";
                levelPrototype.items[5].texture = "ductTape";
                levelPrototype.items[6] = new Item.ItemPrototype();
                levelPrototype.items[6].name = "files";
                levelPrototype.items[6].texture = "files";
                levelPrototype.items[7] = new Item.ItemPrototype();
                levelPrototype.items[7].name = "fire extinguisher";
                levelPrototype.items[7].texture = "fireExtinguish";
                levelPrototype.items[8] = new Item.ItemPrototype();
                levelPrototype.items[8].name = "fortune cookie code";
                levelPrototype.items[8].texture = "fortuneCookieCode";
                levelPrototype.items[9] = new Item.ItemPrototype();
                levelPrototype.items[9].name = "fortune cookie";
                levelPrototype.items[9].texture = "fortuneCookie";
                levelPrototype.items[10] = new Item.ItemPrototype();
                levelPrototype.items[10].name = "gun";
                levelPrototype.items[10].texture = "gun";
                levelPrototype.items[11] = new Item.ItemPrototype();
                levelPrototype.items[11].name = "hammer";
                levelPrototype.items[11].texture = "hammer";
                levelPrototype.items[12] = new Item.ItemPrototype();
                levelPrototype.items[12].name = "keys";
                levelPrototype.items[12].texture = "keys";
                levelPrototype.items[13] = new Item.ItemPrototype();
                levelPrototype.items[13].name = "make-shift bomb";
                levelPrototype.items[13].texture = "makeShiftBomb";
                levelPrototype.items[14] = new Item.ItemPrototype();
                levelPrototype.items[14].name = "notebook";
                levelPrototype.items[14].texture = "notebook";
                levelPrototype.items[15] = new Item.ItemPrototype();
                levelPrototype.items[15].name = "phone";
                levelPrototype.items[15].texture = "phone";
                levelPrototype.items[16] = new Item.ItemPrototype();
                levelPrototype.items[16].name = "soap";
                levelPrototype.items[16].texture = "soap";
                levelPrototype.items[17] = new Item.ItemPrototype();
                levelPrototype.items[17].name = "soda";
                levelPrototype.items[17].texture = "soda";
                levelPrototype.items[18] = new Item.ItemPrototype();
                levelPrototype.items[18].name = "sugar";
                levelPrototype.items[18].texture = "sugar";
                levelPrototype.items[19] = new Item.ItemPrototype();
                levelPrototype.items[19].name = "usb";
                levelPrototype.items[19].texture = "usb";
                levelPrototype.items[20] = new Item.ItemPrototype();
                levelPrototype.items[20].name = "weed killer";
                levelPrototype.items[20].texture = "weedKiller";

                levelPrototype.combinations = new Item.CombinationPrototype[2];
                levelPrototype.combinations[0] = new Item.CombinationPrototype();
                levelPrototype.combinations[0].ingredients = new String[]{"duct tape", "soda", "sugar", "weed killer"};
                levelPrototype.combinations[0].result = "make-shift bomb";
                levelPrototype.combinations[1] = new Item.CombinationPrototype();
                levelPrototype.combinations[1].ingredients = new String[]{"fortune cookie"};
                levelPrototype.combinations[1].result = "fortune cookie code";

                String fileName = "first.json";
                String output = json.prettyPrint(levelPrototype);
                System.out.println(Gdx.files.getExternalStoragePath() + fileName);
                System.out.println(output);
                Gdx.files.external(fileName).writeString(output, false);

                Gdx.app.exit();
            }
        }, new LwjglApplicationConfiguration());
    }
}
